---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: tomcat
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']


- include: local.yml
  tags: tomcat


- name: Install remote ansible data path directory
  tags: tomcat
  file:
    state=directory
    dest={{ remote_ansible_data_path }}


- name: Create Tomcat group
  tags: tomcat
  group:
    state=present
    name={{ tomcat_user_group }}

- name: Create Tomcat user
  tags: tomcat
  user:
    state=present
    name={{ tomcat_user_name }}
    home={{ tomcat_user_home }}
    group={{ tomcat_user_group }}
    createhome=yes
    comment="Tomcat service user"


- name: Copy Tomcat distribution
  tags: tomcat
  copy:
    src={{ local_ansible_data_path }}/{{ tomcat_redis_filename }}
    dest={{ remote_ansible_data_path }}/{{ tomcat_redis_filename }}
    owner=0
    group=0
    mode=0644


- name: Install catalina home directory
  tags: tomcat
  file:
    state=directory
    dest={{ tomcat_env_catalina_home }}
    owner=0
    group=0
    mode=0755

- name: Extract Tomcat installation files to catalina home
  tags: tomcat
  command: tar
      -xzf {{ remote_ansible_data_path }}/{{ tomcat_redis_filename }}
      -C {{ tomcat_env_catalina_home }}
      --strip-components 1
    creates={{ tomcat_env_catalina_home }}/lib


- name: Install catalina base directory and sub dirs
  tags: tomcat
  with_items:
    - conf
    - logs
    - webapps
  file:
    state=directory
    dest={{ tomcat_env_catalina_base }}/{{ item }}
    owner={{ tomcat_user_name }}
    group={{ tomcat_user_group }}
    mode=0755

- name: Register conf files to be installed
  tags: tomcat
  register: tomcat_conf_files
  command: ls -1 {{ tomcat_env_catalina_home }}/conf

- name: Install conf files
  tags: tomcat
  with_items: tomcat_conf_files.stdout_lines
  command: install
    --owner {{ tomcat_user_name }}
    --group {{ tomcat_user_group }}
    --mode 0750
    {{ tomcat_env_catalina_home }}/conf/{{ item }}
    {{ tomcat_env_catalina_base }}/conf/{{ item }}


# Install a tomcat service
- include: service_systemd.yml
  tags: tomcat
  when: ansible_distribution == 'Archlinux'

- include: service_upstart.yml
  tags: tomcat
  when: ansible_distribution == 'Ubuntu'

- include: service_sysvinit.yml
  tags: tomcat
  when: ansible_distribution == 'Debian' or ansible_os_family == 'RedHat'
