---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: tomcat
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']


- name: Install Tomcat download directory (local)
  tags:
    - tomcat
    - download
  local_action: file
    state=directory
    owner=0
    group=0
    mode=2777
    dest={{ ansible_data_path }}

- name: Download Tomcat (local)
  tags:
    - tomcat
    - download
  sudo: no
  local_action: get_url
    dest={{ ansible_data_path }}/{{ tomcat_redis_filename }}
    url={{ tomcat_mirror }}/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/{{ tomcat_redis_filename }}
    mode=0644
    sha256sum={{ tomcat_redis_sha256sum }}


- name: Create Tomcat group
  tags: tomcat
  group:
    state=present
    name={{ tomcat_group }}

- name: Create Tomcat user
  tags: tomcat
  user:
    state=present
    name={{ tomcat_user }}
    home={{ tomcat_home }}
    group={{ tomcat_group }}
    createhome=yes
    comment="Tomcat service user"


- name: Install Tomcat base directory
  tags: tomcat
  file:
    state=directory
    dest={{ tomcat_base }}
    mode=0755
    owner={{ tomcat_user }}
    group={{ tomcat_group }}

- name: Install Tomcat
  tags: tomcat
  unarchive:
    src={{ ansible_data_path }}/{{ tomcat_redis_filename }}
    dest={{ tomcat_base }}


# Tomcat... Another software from the Java world which doesn't have any
#   operating system specific design for separation of concerns, like
#   it's completely okay to write temporary and working data into the
#   installation root of the software.
- name: Hack a usable catalina environment (folders)
  tags: tomcat
  sudo: yes
  sudo_user: "{{ tomcat_user }}"
  when: tomcat_home != tomcat_base
  with_items:
    - conf
    - logs
    - temp
    - webapps
    - work
  file:
    state=directory
    dest={{ tomcat_home }}/catalina/{{ item }}
    mode=0755
    owner={{ tomcat_user }}
    group={{ tomcat_group }}

- name: Hack a usable catalina environment (symlinks)
  tags: tomcat
  sudo: yes
  sudo_user: "{{ tomcat_user }}"
  when: tomcat_home != tomcat_base
  with_items:
    - bin
    - lib
  file:
    state=link
    force=yes
    src={{ tomcat_base }}/apache-tomcat-{{ tomcat_version }}/{{ item }}
    dest={{ tomcat_home }}/catalina/{{ item }}

- name: Hack a usable catalina environment (conf)
  tags: tomcat
  when: tomcat_home != tomcat_base
  with_items:
    - catalina.policy
    - catalina.properties
    - context.xml
    - logging.properties
    - server.xml
    - tomcat-users.xml
    - web.xml
  command:
    install
      --owner {{ tomcat_user }}
      --group {{ tomcat_group }}
      --mode 0644
      {{ tomcat_base }}/apache-tomcat-{{ tomcat_version }}/conf/{{ item }}
      {{ tomcat_home }}/catalina/conf/{{ item }}


# Install a tomcat service
- include: service_systemd.yml
  tags: tomcat
  when: ansible_distribution == 'Archlinux'

- include: service_upstart.yml
  tags: tomcat
  when: ansible_distribution == 'Ubuntu'

- include: service_sysvinit.yml
  tags: tomcat
  when: ansible_distribution == 'Debian' or ansible_os_family == 'RedHat'
