---
- name: Configure init system for Archlinux
  tags: tomcat
  when: ansible_os_family == 'Archlinux'
  include_vars: service/systemd.yml


- name: Configure init system for CentOS <= 6
  tags: tomcat
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version <= '6'
  include_vars: service/sysvinit.yml

- name: Configure init system for CentOS >= 7
  tags: tomcat
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version >= '7'
  include_vars: service/systemd.yml


- name: Configure init system for Debian
  tags: tomcat
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Debian'
  include_vars: service/sysvinit.yml


- name: Configure init system for Ubuntu
  tags: tomcat
  when: ansible_distribution == 'Ubuntu'
  include_vars: service/upstart.yml
