---
# Running services with systemd requires ELF binary.
#   java-jsvc wrappes Java services.
# TODO fixme
- name: Install java-jsvc
  tags: tomcat
  become: yes
  pacman:
    state=present
    name=java-jsvc
    update_cache=no

- name: Install systemd Tomcat Service
  tags: tomcat
  become: yes
  notify: service restart {{ tomcat_service_name }}
  template:
    src={{ tomcat_server_systemd_template }}
    dest=/etc/systemd/system/{{ tomcat_service_name }}.service
    owner=0
    group=0
    mode=0644
