---
- name: Install Tomcat Service
  tags: tomcat
  template:
    src=service_upstart.j2
    dest=/etc/init/tomcat.conf
    owner=root
    group=root
    mode=0644

- include: service_common.yml
  tags: tomcat
